# Generated by Django 6.1.1 on 2026-10-07 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_launch_services'),
        ('provider_search', '0015_servicerequest_no_yes_alert_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('service_areas', models.JSONField(blank=True, default=list)),
                ('sms_opt_out', models.BooleanField(default=False, help_text='Set automatically when they reply STOP. Never text a provider who is opted out.')),
                ('sms_consent_confirmed', models.BooleanField(default=False, help_text="Tick once this provider has agreed to be messaged about client requests (CASL). Providers without it can't be sent offers.")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='providers', to='catalog.service')),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='LeadOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending (not sent yet)'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted (YES)'), ('declined', 'Declined (NO)'), ('expired', 'Expired / no answer')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('reply_channel', models.CharField(blank=True, max_length=10)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('client_phone_shared_at', models.DateTimeField(blank=True, null=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=64)),
                ('followup_sid', models.CharField(blank=True, max_length=64)),
                ('send_error', models.TextField(blank=True)),
                ('hired', models.BooleanField(default=False, help_text='The client hired this provider.')),
                ('hired_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('job_completed', models.BooleanField(default=False)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='provider_search.servicerequest')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='leads.provider')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('service_request', 'provider'), name='one_offer_per_request_and_provider')],
            },
        ),
    ]
