# Generated by Django 6.1.1 on 2026-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='provider_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='response_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='service_radius_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerbusinessprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
