# Generated by Django 6.1.1 on 2026-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_phone', models.CharField(blank=True, max_length=50)),
                ('provider_address', models.CharField(blank=True, max_length=500)),
                ('provider_website', models.URLField(blank=True, max_length=500)),
                ('first_unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('device_id', 'place_id')},
            },
        ),
    ]
