# Generated by Django 6.1.1 on 2026-09-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermatch',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('matched', 'Matched'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('archived', 'Archived')], default='matched', max_length=20),
        ),
    ]
