# Generated by Django 6.1.1 on 2026-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0002_providermatch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('is_available_now', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
