# Generated by Django 6.1.1 on 2026-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0003_provideravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('services', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('is_insured', models.BooleanField(default=False)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
