# Generated by Django 6.1.1 on 2026-09-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0004_provideronboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideronboarding',
            name='license_number',
        ),
    ]
