# Generated by Django 6.1.1 on 2026-09-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0005_remove_provideronboarding_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermatch',
            name='problem_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='providermatch',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('matched', 'Matched'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='matched', max_length=20),
        ),
    ]
