# Generated by Django 6.1.1 on 2026-09-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0006_providermatch_problem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('problem_description', models.TextField(blank=True)),
                ('job_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('job_complexity', models.CharField(blank=True, choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], max_length=20)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('estimated_team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('required_equipment', models.JSONField(blank=True, default=list)),
                ('required_qualifications', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('matched', 'Matched'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='searching', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='providermatch',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_matches', to='provider_search.servicerequest'),
        ),
    ]
