# Generated by Django 6.1.1 on 2026-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0007_servicerequest_providermatch_service_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermatch',
            name='unlock_method',
            field=models.CharField(blank=True, choices=[('subscription', 'Subscription'), ('paid', 'Paid ($4.99)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providermatch',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('found', 'Found'), ('requested', 'Requested'), ('responded', 'Responded'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('matched', 'Matched (legacy)')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('found', 'Found'), ('requested', 'Requested'), ('responded', 'Responded'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('matched', 'Matched (legacy)')], default='searching', max_length=20),
        ),
    ]
