# Generated by Django 6.1.1 on 2026-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0009_relabel_matched_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermatch',
            name='provider_decision',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='provider_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providermatch',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
