# Generated by Django 6.1.1 on 2026-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0011_delete_legacy_search_matches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderAvailability',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New')], default='new', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProviderMatch',
        ),
    ]
