# Generated by Django 6.1.1 on 2026-10-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0012_delete_provideravailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('waitlisted', 'Waitlisted')], default='new', max_length=20),
        ),
    ]
