# Generated by Django 6.1.1 on 2026-10-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0013_servicerequest_waitlisted_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistedRequest',
            fields=[
            ],
            options={
                'verbose_name': 'waitlist demand',
                'verbose_name_plural': 'waitlist demand',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('provider_search.servicerequest',),
        ),
    ]
