# Generated by Django 6.1.1 on 2026-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_search', '0014_waitlisted_request_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='no_yes_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(blank=True, choices=[('today', 'Today'), ('this_week', 'This week'), ('exploring', 'Just exploring')], max_length=20),
        ),
    ]
