# Generated by Django 6.1.1 on 2026-09-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_seed_providers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
