# Generated by Django 6.1.1 on 2026-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_place_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
