# Generated by Django 6.1.1 on 2026-10-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_unlockcredit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UnlockCredit',
        ),
    ]
