# Generated by Django 6.1.1 on 2026-10-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_extended_services_and_outdoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_launched',
            field=models.BooleanField(default=False),
        ),
    ]
